kubeProxyReplacement: strict
k8sServiceHost: kind-external-load-balancer # api server lb
k8sServicePort: 6443                        # api server port
hostServices:
  enabled: true
externalIPs:
  enabled: true
nodePort:
  enabled: true
hostPort:
  enabled: true
image:
  pullPolicy: IfNotPresent
ipam:
  mode: kubernetes
hubble:
  enabled: true
  relay:
    enabled: true